### ISSUE TITLE
Time Problem

### ISSUE THREAD

**Issue by KaizennsamaXD** [Eilaluth/Mocha#1]
Writing commands in less than 2 hours

**Comment by elliottophellia** [comment]
> Writing commands in less than 2 hours

Well sometimes it does happened, I don't really know what the problem, 

Maybe you could try changing the cron schedule with
0 0-23/2 * *

**Comment by elliottophellia** [comment]
https://github.com/elliottophellia/mocha/commit/05e2a8be79b46c292239bfbfc195493da6a10506
